stages:
  - build

build_docker:
  image: costrouc/lammps:stable_16Mar2018-mpi-none
  stage: build
  script:
    - apt update; apt install python3.5 python3-pip
    - wget https://gitlab.com/costrouc/lammps-cython/-/archive/master/lammps-cython-master.tar.gz
    - tar -xf lammps-cython-master.tar.gz
    - pip3 install cython numpy mpi4py
    - pip3 install lammps-cython-master
