stages:
  - test
  - deploy

build_docker:
  image: costrouc/lammps:stable_16Mar2018-mpi-none
  stage: test
  script:
    - apt update; apt install python3.5 python3-pip -y
    - pip3 install cython numpy mpi4py
    - echo "============== Testing Package ============="
    - pip3 install .
    - python3.5 setup.py test
    - echo "============================================"
