stages:
  - test
  - deploy

test:
  image: costrouc/lammps:stable_16Mar2018-mpi-none
  stage: test
  script:
    - apt update; apt install python3.5 python3-pip -y
    - pip3 install cython numpy mpi4py
    - echo "============== Testing Package ============="
    - pip3 install .
    - python3.5 setup.py test
    - echo "============================================"

deploy_docker:
  image: docker:git
  stage: deploy
  services:
    - docker:dind
  script:
    - export DOCKER_IMAGE="costrouc/lammps-cython"
    - export GITLAB_IMAGE="registry.gitlab.com/costrouc/lammps-cython"
    - export BUILD_DIR="."
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_TAG --build-arg VERSION=$CI_COMMIT_TAG $BUILD_DIR
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_TAG $DOCKER_IMAGE:latest
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_TAG $GITLAB_IMAGE:$CI_COMMIT_TAG
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_TAG $GITLAB_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE:latest
    - docker push $GITLAB_IMAGE:$CI_COMMIT_TAG
    - docker push $GITLAB_IMAGE:latest
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
